apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dorisio
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-store.aws.yaml
  - external-secret.aws.yaml
  - service.yaml
  - rollout.yaml
  - hpa.yaml
  - pdb.yaml
  - pvc.yaml
  - servicemonitor.yaml
